language: ruby
os: linux
dist: xenial
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
  latex-beamer git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex Softwaretests.tex
- pdflatex Softwaretests.tex
- pdflatex BlackBoxTestverfahren.tex
- pdflatex WhiteBoxTestverfahren.tex
deploy:
  provider: releases
  token:
    secure: dqjWoKLp/D9uRNtrnQHf+civPENCpShFp0MvEFBvSlz0pfrC19RMuKz6W5OZUidu6YWz+279xi7Fc31i0jwErGB2lpX+0JUc5AA/9a4Fz/jM6ERsKDCGomDEj3MUNakIqD++yQHnu1ZMPHF+bLa+528wJBe7ZKEoxu8+jUPatwiSqq60U9uxG/7ftWdXcRX7ELWf/oKeIwNGWL4okGB120OKvjGgWXR3hyoPUWtreeNSalXBywkonAouiMLQd9dov1pVR9d7unh3mNgIBN+qQFwU2D/5TzlppecfBHQBxw3awdHnBrAPgXddrQ+E9Yf/eH+ooY5bImdUi0XC+JI6oYXJP757Vxt1kAMUxBw4CJ4aptC+8lgz6PmRYkaGgeewJS5JDVJFnyKTUCmbMX+wjIGkBPtbzfVMTJz7UdllIoICSUz3gIRcyMdwspWRi8KUeyUz1nyWP9lhD7+Lb0kisEqA+/ab/vp7Yck89V13E1jrbfML7vg98bBkNqCHh9AnWD6+2bAR54rg0lerqJR37v6hdhX3SjrO+LTDCTjGgQCTIZ2/Ei6T/OSlNK6IXyay/tDd+dhDQbdukRQ98Si2EIgcDt9Wu3yZefm7OxlozWSj6DlPY5WMZB5rNp6Q1NNv/wdZfCgpXYXiBEW6siVQXi1Q4wulBByk7cR2gEJKXZE=
  file:
  - Softwaretests.pdf
  - BlackBoxTestverfahren.pdf
  - WhiteBoxTestverfahren.pdf
  cleanup: true
  draft: false
  prerelease: true
  overwrite: true
  on:
    repo: mflingelli/Softwaretests-Grundlagen
    tags: true
    branch: master
env:
  global:
    secure: BTJpfC61WRDdkprXYA8+FsSEU13MAW72fq353eumjo5KRxoKxL8qt5L3yy9falF5t5x05GooB4TCzaa0/GLoYUme0gumU9xJ5CfVjiL6ukyBJ9w7MAt5O8G9sfV+ykqLnn3cjl65++996qEgiXlKZNQNFSOPDImTqS86Pl4TaJzrt/2oA07jLJtig1FEg7UYl062ozg2HXEb0Yy1YkdiWBV+cq6Q5rfxYgIqzLYdEd+JvDHLEAu2Uz7RQrXrm8SpaxkdazpGiaNlfsC5I/mgAudrJ4qMfLlVLooTbfKRflL8Piq2YNsU2cczikaR3qcuufBhE8WEOQ9f28gakvbl7loyJh5QxFVelytk8ZSxS2G9V+qGf0skO9h0Ofr7TZ5rs6PjWGcSbn/MyW3yUMuOL5V5yNEJ1lJLhz66yJsG6rZRlNH0VjgPsC1BPTtrFLBS5EMPI0OAFeeA0cL9JRAqzYRrxzuv90qFNw+eRhaJDsbAbcO2hRigD5t9+pFyYFaW8TEPdodLsrcnm3MbgG1Yy6BRy2pbrGszVq9LVdMW5vyZqHULOMzxSecpURnvLzvUwS7Q9jYZjE04+E4YtClWLeAQ0vaYuQYK9sgwbnNzkvbhH5/oxQNb5EDs4Gw97AB9XEebgI0keMCyQgiVTIbkgwqgVClVHZ0zF3EI8V5grMQ=
