sudo: required
language: ruby
dist: xenial
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
  latex-beamer git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex Softwaretests.tex
- pdflatex Softwaretests.tex
deploy:
  provider: releases
  api_key:
    secure: Gi5qoC5JmaD4/xPOk0ga0O6u/kW0hH+TzQRQ7Nb8+zNGblAk7aIVl9ao7Mo+K1c1fdrhltD+uJlKoVUA+UtyvgnShY+D4gPhkWFBcqMSv2TUZ5l1NYDf3Hn+4CWAYVdHEL4ADuwQPhp03dLmRP6+VFCvOO7T7Def1mLHPqHHMk2MNtQK5w0LE9uEFWUj0u8HzgeoqmGRgMz/5oogXzJcHA75nlRWZ4J09ynGEX6LsQ2/uKjs0Phuu2LqNZpYLCCds6tlKyZdXRgZwgme7SQGjMnQQHCR3jB04whDbqm0JaXGPNqSicxwh4Rpz0dXE/pDBmHgZeEWhkU0p1nzEGiC4rnFgBzHhZtbXB29lCiGVHmr+TfbX33l/3tpX7as9tnNB9/BMpTnrzwSa6zD8RwRsANzwjW1HgKxZz1wdlblAuA6vqEkSJcuwRaL2ifqTE0//BPsbCyPrDeH79WVwLXwtBc0ZUmfSOduguwnItUpCTm42RE+6OklX+mrVYAIG0BdOkA5w0CU8MfH/O7nZ6NFu1uEjd6olOJnkA8ONJsxbTX3sPSozydUcwoEXeAI8h0WBYeuWKUBDHi7TALs1N/wYnmvLKyoIW5DOMIy7LUV00SpQuphi5XEz2oYBCPCm1M8qi4u/xnbYfpt5/jh6MKMaH9X0/HEfL2lLMwZCTrEw6I=
  file:
  - Softwaretests.pdf
  skip_cleanup: true
  draft: false
  overwrite: true
  on:
    tags: true
    repo: mflingelli/Softwaretests-Grundlagen
    branch: master
env:
  global:
  - secure: Gi5qoC5JmaD4/xPOk0ga0O6u/kW0hH+TzQRQ7Nb8+zNGblAk7aIVl9ao7Mo+K1c1fdrhltD+uJlKoVUA+UtyvgnShY+D4gPhkWFBcqMSv2TUZ5l1NYDf3Hn+4CWAYVdHEL4ADuwQPhp03dLmRP6+VFCvOO7T7Def1mLHPqHHMk2MNtQK5w0LE9uEFWUj0u8HzgeoqmGRgMz/5oogXzJcHA75nlRWZ4J09ynGEX6LsQ2/uKjs0Phuu2LqNZpYLCCds6tlKyZdXRgZwgme7SQGjMnQQHCR3jB04whDbqm0JaXGPNqSicxwh4Rpz0dXE/pDBmHgZeEWhkU0p1nzEGiC4rnFgBzHhZtbXB29lCiGVHmr+TfbX33l/3tpX7as9tnNB9/BMpTnrzwSa6zD8RwRsANzwjW1HgKxZz1wdlblAuA6vqEkSJcuwRaL2ifqTE0//BPsbCyPrDeH79WVwLXwtBc0ZUmfSOduguwnItUpCTm42RE+6OklX+mrVYAIG0BdOkA5w0CU8MfH/O7nZ6NFu1uEjd6olOJnkA8ONJsxbTX3sPSozydUcwoEXeAI8h0WBYeuWKUBDHi7TALs1N/wYnmvLKyoIW5DOMIy7LUV00SpQuphi5XEz2oYBCPCm1M8qi4u/xnbYfpt5/jh6MKMaH9X0/HEfL2lLMwZCTrEw6I=
