language: ruby
os: linux
dist: xenial
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
  latex-beamer git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex Softwaretests.tex
- pdflatex Softwaretests.tex
- pdflatex BlackBoxTestverfahren.tex
- pdflatex WhiteBoxTestverfahren.tex
deploy:
  provider: releases
  token:
    secure: QsNGglOUKRTUDIybGAkNFXEFcab5EAdP5xQzV/TgnZ5ovsDHsMnd3fA1o1VWxKXM0qkKbo4psjpo6G69bfa54cepyyQOXlO2x8OhUnX84/vj6zoZaC/78rdMPJ3FUUEfxk90YgPrGbC4ijV66zmw70N5AcR2GW7W8EuYzCJ5iuf0jQiVxczvS6p+A4QHOuy06P7Z0ujkTur8ZR7aLBI1I/z2tzPyLSLX4wQOWLwNHs3jhNNDKUQkPEQj9PATB+/q5gQCzQVCD3/pJjlfzktILzgHQDbObeDeNmkyQGcGlNvmQDX5Kq967XfJc+9WJyB2YS9c7YqIFNxVow4L7PBdkJXAvzOpPuxZLB8KwnZWiJCNWBqsmfqMgshTzQyGZ1GyplIk6gT9J61r4y/CHirvVOK2FsR02rOcNWR3DG5Z5JJFs3IQ9LdB68NtyFez23RfXMFbGc0uGjBeFTICraqXQyDOF1Rwe77AHV+HFYphFm0Lmah2Eeh9ykr46FlkrlN/HKAucom9QY/xMy8A1d3NXgE56f0rakcpI4G7SaUQOQcmrH8TgfGdLt9eWzeYVzRhc1bnEwmxwWM9WwxNKb7BMQqeqPkXidxK7D2VKRvfrjlv6mb/YYLzAHVHTr/DfsNS1OLfWkrhRTj8Lz/zfKBBXiGK3r9HmaQkf4mJp/OAFxQ=
  file:
  - Softwaretests.pdf
  - BlackBoxTestverfahren.pdf
  - WhiteBoxTestverfahren.pdf
  skip_cleanup: true
  draft: false
  prerelease: true
  overwrite: true
  on:
    repo: mflingelli/Softwaretests-Grundlagen
    tags: true
    branch: master
env:
  global:
    secure: dNwvqMH40j+9b+uodmIcd8gjmCrWrWtjqU6VRYODGOOzU3/ZF8NhDvHsnbUaKrN//1C/GG723kTpJoMLlQSmyoGvKxW9nBBM9N3v+IgjjWaq6dMhfpb26hzos+ba1JA1/xZYbB8beE3DtFO6DLObVhS9A3TwrZ6NDsvZSFHEjyTDDhU5+mKkfyEoYB93cqSvsbvYeLyLLiEBASP5e3n02r1LJM/6mm7sxqhBKA6MPLap4gO4zyrWzv+QoPOM6tyUMRldE1o365vHmM6ZBg+O0RQmoWUylC9MjbF+daMzunIzILUA9cpcZuzeQsOaKybKM1E3LJkAQlC3kUiTZjhekIJvcRJCYOuKZQJF9FckU1JXgcWbrrz95CJKwR5mFTUkfFC6U7ZOvG2128OglrRPsMC3sI3mYhPgWurnuGR/NbhhK1TSgdfPDLOGTp/9R5VnJQLyW+9g0PjyBIAYTGfKzrV2qdyk10y9KR3YxNiprXSfZmcT8QHPPzdVBkmU0uRDrxYutl5vtbd+3WffTeWf3E5ra1naRMbvP04iD8dLFJfqBhDirDv7xl9p4XOP8usM54pSwcUr0zEfXWJCXNMkUUwHeUkr9Xweys82aAyICctTW5UlbK58NPKiqxpKQRUaweL6asVIUecIMJT0O7UWO25BkKKwZzYxbi/gR6lUxVc=
