sudo: required
language: ruby
dist: xenial
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
  latex-beamer git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex Softwaretests.tex
- pdflatex Softwaretests.tex
- pdflatex Uebungen/BlackBoxTestverfahren.tex
- pdflatex Uebungen/WhiteBoxTestverfahren.tex
deploy:
  provider: releases
  api_key:
    secure: RE2CWMj1V+zJP/RYmNS8Ui7i8+/7xcskxoVSCrX6VxRNn8XhB7Gi6O9zvsMVUd9XFLMVN9NfYGi+P1XF5l+FmNgk2JpgLAIKg/QzqmKxt59vOCnnpNxza1y0Bty45h3rBEky1U92MCEVkCH+y4tuHqLrNB/ocusdCboMHSuOQWnOz0Uo/5WuM+6hBeIEvQiBkpnpzZAjxFF67nHk+vECy3SetES5l5CuI49CQiw4QyiLuvMikX7GYFiGV0oZJTh4bnFXPjxGBrmYzM24phZfvwLQs85A5ML/XR+Bg6ViSVfGwORIzQiLz1cyT0FaF2W/XUeHbNKPpxS938JQttssTVwGdkOOfdnfzm41s3zwRmadurRHy0HfvE7OtkZK8pvSx3w2Z7ATa5o5eOCgO6miLJhFbCgh1YET7UuqVw1nr5gdFq4Cqz+xZAjrlXUe2PHwR4+of/IQlGb0+wjmKdqVCyNQ9MptRBZJbf9LzpeUQ4Imenz0fzUwVuNHvp9rKwUG/kO97pSXKhcgZY7KbZ9VPtTTVgNfdJvThevD+l9wbatT4Uev/2pYlRD9sMgDHlKZZ0z3FdTp1qYMl9MzJyo/Qe+V9R4+HpTQLLnwI8YCl+c9uaOl8knlJKAIISh4T9yAoDKBbPMYwpOxNgvbNyoTGJRzw4pVkICeJ/1MtdDlEZs=
  file: 
    - Softwaretests.pdf
    - Uebungen/BlackBoxTestverfahren.pdf
    - Uebungen/WhiteBoxTestverfahren.pdf
  skip_cleanup: true
  draft: false
  overwrite: true
  on:
    repo: mflingelli/Softwaretests-Grundlagen
    tags: true
    branch: master
env:
  global:
  - secure: Jdxuapygc7tkB0FRaS3pU6EyLiyXJ8xXEz6xyWyJkEouflRg7qwunuzwjxZ5RBQRpIykmYZWr9d+1xvrTM5KhDfK1G+RH+XFX4VVVkIRbSZ6yQ7Ww1/2uZcHU5Iy2oUdIyrECDfDKmsQGU8xqQ8drtQWZykL5MHAA4EycDWXzSbdjVX9GbUTN66ChMb/pGmZ2pBqlc+4QIowLvmRSz8Tqd32bu3yv05v7MQZ3VVunVInkXu6F9/2Aq9iOfT+sXvk4OhKgaK5f2OOkPf8LvD6H4IWkOuI+xvVfuA0MEu/1X1ffcT3Y3HcwuL+ljxrGXooxHlqzoW5PD/8T/mP1GnBIHvplRcuyLqpOGczt1+dyWVSnA+aXFKQTZ1zaEJY0C6DxO3yRbaXSFO3qdUcElMhkV+Bi0vyA4gcmBzQtt13YVWkY7vZLtKeUDiqBCGwlt9V86QieImQFOiSjTrSK7xzBs3b3yecNCrFJNKgHqXmIoHOV09dX+uWuzlp+CFJXlwm9rkgdPBptvX/KIoPTljknia2kJ661St8N11G0nGXHxcIoLQ2+FjooBm2ohV5rC2hbUiBuMwL3rtlZj3avhaVwf2nt8jOPlkafl2x+8py0DDnzk9KkDE6y/b2Hd4+C2LKtvTOfAEosERHCNexaLYxPmFMzH213hEzR9c/p7eF8Lc=
