language: ruby
os: linux
dist: xenial
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
  latex-beamer git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex Softwaretests.tex
- pdflatex Softwaretests.tex
- pdflatex BlackBoxTestverfahren.tex
- pdflatex WhiteBoxTestverfahren.tex
deploy:
  provider: releases
  token:
    secure: YYw+2w+N0PzhNl+80DNn/+fBFeJkHe2QQ0Rad7Dt4c4HUui6lFITWefQ2PWJG2wv14FGvnzy1jZaq2KVZPzb/NHhvZVoEgr/KOumPQAFyadqZDkcxBhVKdBx2V89OKvy1vpZRYiJFec5H8empHsDI7dG4jhl2ShqwDaAzIrrRtnXB7seX8DLR0rA0ai9K8JHygKFx7KMKB0bBbuLpr9sNczIopzEoFVQM/eMCA+LXfWiCmm8P6MC4kycDULzTmcBRMcYJO80TUsqxY3VyFj+WuDQsUGBsB58x1L+cznUgcv1XuOsOFMb+cSb5dhBNNoEU7ImmEu1OR1QGf/ftlDnZzrOqFZJ8D6EGnEWf6FqAYzv98iMIIpC6gYN7DTSaOXKX4tToMrXW+7QizZ2Zp2UJ2d1X6y2sX/fQypJ6adtnc6ExjukNQM88PjFC+j9uObuZqOzLi2m18Bym1W/RIN+sfWpWopBY2mXaYheuZVPbhrBTPfsRxxhKQYvt03eHZiikqQvJcS17R1cOcMC+5QEszInsVyMSMWWekPx/2l7+VDo8gDm7R7oPCIGs0nwVxjN7iXcXCyzIffFZ210w+yj2jZ9QBvlPASHBAIsWvjggMd5hbwO2bgDwb1mKgCevuHzzYfS16q17H9fLJ0myljg4zsrurbPTqCM9BQBlz1WwEk=
  file:
  - Softwaretests.pdf
  - BlackBoxTestverfahren.pdf
  - WhiteBoxTestverfahren.pdf
  cleanup: true
  draft: false
  prerelease: true
  overwrite: true
  on:
    repo: mflingelli/Softwaretests-Grundlagen
    tags: true
    branch: master
env:
  global:
    secure: BTJpfC61WRDdkprXYA8+FsSEU13MAW72fq353eumjo5KRxoKxL8qt5L3yy9falF5t5x05GooB4TCzaa0/GLoYUme0gumU9xJ5CfVjiL6ukyBJ9w7MAt5O8G9sfV+ykqLnn3cjl65++996qEgiXlKZNQNFSOPDImTqS86Pl4TaJzrt/2oA07jLJtig1FEg7UYl062ozg2HXEb0Yy1YkdiWBV+cq6Q5rfxYgIqzLYdEd+JvDHLEAu2Uz7RQrXrm8SpaxkdazpGiaNlfsC5I/mgAudrJ4qMfLlVLooTbfKRflL8Piq2YNsU2cczikaR3qcuufBhE8WEOQ9f28gakvbl7loyJh5QxFVelytk8ZSxS2G9V+qGf0skO9h0Ofr7TZ5rs6PjWGcSbn/MyW3yUMuOL5V5yNEJ1lJLhz66yJsG6rZRlNH0VjgPsC1BPTtrFLBS5EMPI0OAFeeA0cL9JRAqzYRrxzuv90qFNw+eRhaJDsbAbcO2hRigD5t9+pFyYFaW8TEPdodLsrcnm3MbgG1Yy6BRy2pbrGszVq9LVdMW5vyZqHULOMzxSecpURnvLzvUwS7Q9jYZjE04+E4YtClWLeAQ0vaYuQYK9sgwbnNzkvbhH5/oxQNb5EDs4Gw97AB9XEebgI0keMCyQgiVTIbkgwqgVClVHZ0zF3EI8V5grMQ=
